export const banner = `// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable`

export const padding = " ".repeat(4)

export function sortUnique(values: string[]): string[] {
    return Array
        .from(new Set(values))
        .sort((a, b) => a.localeCompare(b, "en-US"))
}

export function printBarrel(sections: string[]): string {
    const contents = [banner, ...sections]
        .filter(Boolean)
        .join("\n\n")
    return `${contents.trim()}\n`
}
